"""Static checks on the GitHub Actions workflows.

A broken shell block in a workflow costs a full CI round trip to discover, and a
tag-pinned action or a hardcoded version is easy to reintroduce. These checks are
cheap and run in the normal test suite.

One pipeline — .github/workflows/build-candidate.yml — builds every platform from
one commit and is the only workflow allowed to publish. The retired per-platform
workflows (build-windows.yml, build-linux.yml) must never come back on any ref:
a second publish path is how unverified bytes once reached a tagged release.
scripts/check-publish-paths.sh enforces that against every remote head, not
only the local checkout — see PublishPathSweepTests below.

Skipped when PyYAML is unavailable (it is deliberately NOT an application
dependency); CI installs it for the source job so the checks do run there.
The sweep tests do not need PyYAML: they run the script itself.
"""

import pathlib
import re
import subprocess
import tempfile
import unittest

from support import bash_syntax_check, find_build_recipe, run_bash_file, run_bash_script
from workflow_harness import evaluate_if

try:
    import yaml
except ImportError:  # pragma: no cover - depends on the environment
    yaml = None

ROOT = pathlib.Path(__file__).resolve().parent.parent
# The checkout keeps the canonical workflow under .github; the source archive
# keeps the generated copy at ci/build-candidate.yml. Pick whichever exists so
# these checks also run against the archived source, which is where an
# incomplete archive shows up.
ACTIVE = ROOT / ".github/workflows/build-candidate.yml"
if not ACTIVE.is_file():
    ACTIVE = ROOT / "ci/build-candidate.yml"


def all_workflows() -> list[pathlib.Path]:
    """Every workflow recipe, from the checkout or the extracted archive."""
    folder = ROOT / ".github" / "workflows"
    if not folder.is_dir():
        folder = ROOT / "ci"
    return sorted(folder.glob("*.yml"))


@unittest.skipIf(yaml is None, "PyYAML not installed; workflow lint skipped")
class WorkflowConfigTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.text = ACTIVE.read_text(encoding="utf-8")
        cls.data = yaml.safe_load(cls.text)

    def test_the_workflow_has_exactly_one_source_of_truth(self):
        """One canonical workflow, and no committed duplicate of it.

        scripts/build-source.sh copies the workflow into the archive as
        ci/build-candidate.yml. Keeping a second committed copy meant two files
        that had to be kept byte-identical by hand; the archive copy is generated
        now, so a committed one is drift waiting to happen.
        """
        self.assertTrue(ACTIVE.is_file(), "no workflow recipe found")
        checkout = ROOT / ".github/workflows/build-candidate.yml"
        if checkout.is_file():
            self.assertFalse(
                (ROOT / "ci/build-candidate.yml").is_file(),
                "ci/build-candidate.yml is generated by scripts/build-source.sh "
                "and must not also be committed as a second source of truth",
            )

    def test_every_shell_block_parses(self):
        checked = 0
        for job, spec in self.data["jobs"].items():
            for index, step in enumerate(spec.get("steps", [])):
                script = step.get("run")
                if not script:
                    continue
                if step.get("shell") == "pwsh":
                    # PowerShell is not bash; the Windows runner executes it.
                    continue
                checked += 1
                result = bash_syntax_check(script)
                label = f"{job}/{step.get('name') or f'step {index}'}"
                self.assertEqual(result.returncode, 0,
                                 f"{label} has invalid shell:\n{result.stderr}")
        self.assertGreater(checked, 5, "expected to lint the workflow's shell blocks")

    def test_every_workflow_file_lints_and_pins_actions(self):
        """The inputs producers get the same scrutiny as the release pipeline."""
        recipes = all_workflows()
        self.assertGreaterEqual(len(recipes), 3,
                                "build-candidate plus the two inputs workflows")
        for recipe in recipes:
            text = recipe.read_text(encoding="utf-8")
            data = yaml.safe_load(text)
            with self.subTest(workflow=recipe.name):
                for reference in re.findall(r"uses:\s*(\S+)", text):
                    self.assertRegex(
                        reference, r"^[\w.-]+/[\w.-]+@[0-9a-f]{40}$",
                        f"{recipe.name}: actions must be pinned to a full commit SHA")
                for job, spec in (data.get("jobs") or {}).items():
                    for step in spec.get("steps", []):
                        script = step.get("run")
                        if not script or step.get("shell") == "pwsh":
                            continue
                        result = bash_syntax_check(script)
                        self.assertEqual(
                            result.returncode, 0,
                            f"{recipe.name}/{job} has invalid shell:\n{result.stderr}")

    def test_actions_are_pinned_to_commit_shas(self):
        uses = re.findall(r"uses:\s*(\S+)", self.text)
        self.assertTrue(uses)
        for reference in uses:
            with self.subTest(action=reference):
                self.assertRegex(
                    reference, r"^[\w.-]+/[\w.-]+@[0-9a-f]{40}$",
                    "actions must be pinned to a full commit SHA, not a tag")

    def test_runner_images_are_pinned_not_floating(self):
        """CT-17: a `-latest` label silently changes the build environment.

        Every runs-on in every recipe must name a specific image. The release
        this closes was built on whatever `ubuntu-latest`/`windows-latest`
        happened to mean that week.
        """
        pinned = re.compile(
            r"runs-on:\s*(ubuntu-\d+\.\d+|windows-\d{4}|macos-\d+)\s*$")
        for recipe in all_workflows():
            text = recipe.read_text(encoding="utf-8")
            labels = [line.strip() for line in text.splitlines()
                      if line.strip().startswith("runs-on:")]
            self.assertTrue(labels, f"{recipe.name} has no runs-on to pin")
            for label in labels:
                with self.subTest(workflow=recipe.name, label=label):
                    self.assertNotIn("-latest", label,
                                     "runner images must not float on a -latest alias")
                    self.assertRegex(label, pinned)

    def test_no_version_number_is_hardcoded(self):
        # The version is read from version.py, so bumping it needs no workflow edit.
        self.assertNotRegex(self.text, r"\b0\.1\.\d+\b",
                            "the workflow must not hardcode a version")

    def test_release_is_not_tag_gated_and_not_a_prerelease(self):
        # The owner asked for a plain release, triggered by explicit dispatch.
        self.assertNotIn("--prerelease", self.text)
        self.assertNotIn("--clobber", self.text)
        release = self.data["jobs"]["release"]
        # Gated on the dispatch input, never on a tag or a ref pattern: the tag
        # is what publishing creates, so it cannot also be what triggers it.
        self.assertEqual(release["if"], "${{ inputs.publish }}")
        self.assertNotIn("refs/tags", release["if"])
        self.assertEqual(release["permissions"], {"contents": "write"})

    def test_network_check_also_runs_without_ambient_trust(self):
        """Guards the check that caught the bundled-trust-store regression."""
        self.assertIn("SSL_CERT_DIR=/nonexistent/certs", self.text,
                      "CI must re-verify HTTPS with the host's CA configuration "
                      "removed, so only the bundled trust store can make it pass")

    def test_a_published_version_is_never_rebuilt(self):
        """Overwriting a published tag changes artifacts somebody already
        downloaded and verified. The publish step must refuse, not delete."""
        self.assertNotIn("gh release delete", self.text)
        self.assertIn('git ls-remote --exit-code --tags origin "refs/tags/$tag"', self.text)
        self.assertIn("Bump version.py", self.text)

    def test_release_checks_downloaded_bytes_before_any_publish(self):
        self.assertIn("shasum -a 256 -c SHA256SUMS", self.text)
        self.assertLess(self.text.index("shasum -a 256 -c SHA256SUMS"),
                        self.text.index("gh release create"))

    def test_dependency_installation_finishes_before_signing_material(self):
        self.assertNotIn("pip install --quiet", self.text)
        self.assertGreaterEqual(
            self.text.count("pip install --require-hashes -r requirements-ci.lock"), 3,
            "the source, macOS and Linux jobs all install the locked CI dependencies")
        self.assertNotIn("brew install", self.text)
        macos = self.data["jobs"]["macos"]["steps"]
        names = [step.get("name", "") for step in macos]
        signing = names.index("Import the Developer ID certificate")
        preparation = names.index("Prepare hash-locked build environment before signing secrets")
        self.assertLess(preparation, signing)
        self.assertIn("PREPARE_ONLY=1", macos[preparation]["run"])
        build_step = next(step for step in macos if step.get("name") == "Build the DMG")
        self.assertEqual(build_step["env"]["BUILD_DEPS_PREPARED"], "1")
        for step in macos[signing + 1:]:
            script = step.get("run", "")
            self.assertNotIn("pip install", script)
            self.assertNotIn("brew install", script)
        self.assertNotIn('echo "KEYCHAIN_PASSWORD=', self.text)

    def test_only_manual_dispatch_can_publish(self):
        """A source push must not publish a money-moving desktop app."""
        trigger = self.data.get("on", self.data.get(True))
        self.assertIn("workflow_dispatch", trigger)
        self.assertNotIn("push", trigger)
        inputs = trigger["workflow_dispatch"]["inputs"]
        self.assertIs(inputs["publish"]["default"], False)
        self.assertIn("Refuse an unsigned public release", self.text)
        self.assertIn("Refusing to publish an unsigned or unnotarized build", self.text)

    def test_publication_is_restricted_to_the_default_branch(self):
        guard = next(step for step in self.data["jobs"]["version"]["steps"]
                     if step.get("name") == "Require the default branch for publication")
        self.assertEqual(guard["if"], "${{ inputs.publish }}")
        self.assertIn('refs/heads/main', guard["run"])
        self.assertIn("CANDIDATE_RUN_ID", guard["run"])
        self.assertEqual(
            guard["env"]["CANDIDATE_RUN_ID"], "${{ inputs.candidate_run_id }}",
            "the run id must arrive through env:, never as script text (CT-72)")

    def test_versioned_release_notes_are_included_when_present(self):
        self.assertIn('release_notes="releases/RELEASE-NOTES-${VERSION}.md"', self.text)
        self.assertIn('cat "$release_notes" >> notes.md', self.text)

    def test_publication_promotes_a_successful_notarized_candidate_from_same_commit(self):
        checksums = self.data["jobs"]["checksums"]
        self.assertIn("actions", checksums["permissions"])
        promote = next(step for step in checksums["steps"]
                       if step.get("name") == "Download and verify the tested candidate artifacts")
        self.assertEqual(promote["if"], "${{ inputs.publish }}")
        self.assertEqual(promote["env"]["GH_REPO"], "${{ github.repository }}")
        for required in (
                "gh api", "gh run download", "head_sha", "conclusion", "head_branch",
                '.path == ".github/workflows/build-candidate.yml"',
                "CANDIDATE-MANIFEST.txt", "notarize=true", "publish=false",
                "shasum -a 256 -c SHA256SUMS"):
            with self.subTest(required=required):
                self.assertIn(required, promote["run"])
        release = self.data["jobs"]["release"]
        download = next(step for step in release["steps"]
                        if step.get("uses", "").startswith("actions/download-artifact"))
        self.assertEqual(download["with"]["name"], "release-assets")
        verify = next(step for step in release["steps"]
                      if step.get("name") == "Verify downloaded release bytes")
        publish = next(step for step in release["steps"]
                       if step.get("name") == "Publish the release")
        self.assertLess(release["steps"].index(verify), release["steps"].index(publish))
        self.assertIn("CANDIDATE-MANIFEST.txt", self.text)

    def test_a_candidate_dispatch_builds_without_publishing(self):
        """Building and publishing are separate acts.

        Publishing is irreversible by policy: a published tag is never rebuilt. That
        made the first dispatch of a version the point of no return, so the only way
        to correct an artifact nobody had opened yet was to bump the version. The
        candidate path must leave before the release step creates anything, and
        an ordinary dispatch must stay nonpublishing.
        """
        trigger = self.data.get("on", self.data.get(True))
        inputs = trigger["workflow_dispatch"]["inputs"]
        self.assertIn("publish", inputs)
        self.assertIs(inputs["publish"]["default"], False,
                      "an ordinary dispatch must build only a candidate")
        self.assertIs(inputs["notarize"]["default"], False)
        # Building and publishing are separate jobs, split by least authority
        # (CT-83): the candidate job can never create a release, and the publish
        # job cannot run on a candidate dispatch. The notes and the release
        # command belong to the publish job alone.
        candidate = self.data["jobs"]["candidate-manifest"]
        self.assertEqual(candidate["if"], "${{ !inputs.publish }}")
        self.assertEqual(candidate["permissions"], {"contents": "read"})
        candidate_runs = "\n".join(step.get("run", "") for step in candidate["steps"])
        self.assertIn("CANDIDATE-MANIFEST.txt", candidate_runs)
        self.assertNotIn("gh release create", candidate_runs,
                         "the candidate job must not be able to publish")
        notes = self.text.index("cat > notes.md <<EOF")
        publish = self.text.index("gh release create")
        self.assertLess(notes, publish, "the notes must be built before the release command")
        self.assertIn("was built and NOT published", self.text)
        # A candidate is not a draft release and not a prerelease: it creates no
        # release object at all, so there is nothing to publish by accident.
        self.assertNotIn("--draft", self.text)

    def test_one_pipeline_builds_every_platform_from_one_commit(self):
        """The three platform jobs share one run, one commit, one sums file."""
        jobs = self.data["jobs"]
        for job in ("version", "source", "macos", "windows", "linux",
                    "checksums", "candidate-manifest", "release"):
            self.assertIn(job, jobs)
        self.assertEqual(jobs["checksums"]["needs"],
                         ["version", "source", "macos", "windows", "linux"])
        self.assertEqual(jobs["candidate-manifest"]["needs"],
                         ["version", "source", "macos", "windows", "linux", "checksums"])
        self.assertEqual(jobs["release"]["needs"],
                         ["version", "source", "macos", "windows", "linux", "checksums"])
        self.assertEqual(jobs["windows"]["runs-on"], "windows-2022")
        self.assertEqual(jobs["linux"]["runs-on"], "ubuntu-24.04")
        self.assertEqual(jobs["macos"]["runs-on"], "macos-15")

    def test_platform_artifacts_have_distinct_names_and_suffixed_sboms(self):
        self.assertIn("name: windows-bundle", self.text)
        self.assertIn("name: linux-desktop", self.text)
        self.assertIn("BUILD-SBOM-windows-x64.json", self.text)
        self.assertIn("BUILD-SBOM-linux-x86_64.json", self.text)
        for step_name in ("Download current Windows bundle for a nonpublishing candidate",
                          "Download current Linux assets for a nonpublishing candidate"):
            step = next(step for step in self.data["jobs"]["checksums"]["steps"]
                        if step.get("name") == step_name)
            self.assertEqual(step["if"], "${{ !inputs.publish }}")

    def test_the_publish_verification_counts_every_platform(self):
        promote = next(step for step in self.data["jobs"]["checksums"]["steps"]
                       if step.get("name") == "Download and verify the tested candidate artifacts")
        for required in (
                "-name '*.tar.gz' | wc -l | tr -d ' ')\" = 2",
                "-name '*.dmg' | wc -l | tr -d ' ')\" = 1",
                "-name '*.zip' | wc -l | tr -d ' ')\" = 1",
                "-name '*.AppImage' | wc -l | tr -d ' ')\" = 1",
                "test -f BUILD-SBOM-windows-x64.json",
                "test -f BUILD-SBOM-linux-x86_64.json"):
            with self.subTest(required=required):
                self.assertIn(required, promote["run"])

    def test_the_checksum_manifest_is_gpg_signed_on_the_publish_path(self):
        """SHA256SUMS is CI-generated; its signature proves which key released it."""
        sign = next(step for step in self.data["jobs"]["checksums"]["steps"]
                    if step.get("name") == "Sign the checksum manifest with the release key")
        self.assertEqual(sign["if"], "${{ inputs.publish }}")
        self.assertIn("GPG_PRIVATE_KEY", sign["run"])
        self.assertIn("SHA256SUMS.asc", sign["run"])
        self.assertIn("SIGNING.md", sign["run"])
        release_verify = next(step for step in self.data["jobs"]["release"]["steps"]
                              if step.get("name") == "Verify downloaded release bytes")
        self.assertIn("gpg --verify SHA256SUMS.asc SHA256SUMS", release_verify["run"])
        self.assertIn("signing-key.asc", release_verify["run"])

    def test_every_asset_carries_a_sigstore_build_attestation(self):
        checksums = self.data["jobs"]["checksums"]
        self.assertEqual(checksums["permissions"].get("id-token"), "write")
        self.assertEqual(checksums["permissions"].get("attestations"), "write")
        attest = next(step for step in checksums["steps"]
                      if "attest-build-provenance" in step.get("uses", ""))
        self.assertRegex(attest["uses"], r"@[0-9a-f]{40}$")
        self.assertEqual(attest["with"]["subject-path"], "dist/*")

    def test_no_second_publish_path_exists(self):
        """The retired per-platform workflows stay retired.

        This is the LOCAL half of the check. It only sees the checkout, which
        is exactly why build-windows.yml survived on windows-port through two
        audit cycles — see PublishPathSweepTests for the remote half.
        """
        self.assertFalse((ROOT / ".github/workflows/build-windows.yml").is_file(),
                         "build-windows.yml is retired; the unified pipeline builds Windows")
        self.assertFalse((ROOT / ".github/workflows/build-linux.yml").is_file(),
                         "build-linux.yml is retired; the unified pipeline builds Linux")
        for recipe in all_workflows():
            if recipe.name == "build-candidate.yml":
                continue
            self.assertNotIn("gh release create",
                             recipe.read_text(encoding="utf-8"),
                             f"{recipe.name} must not publish a release")

        sweep = ROOT / "scripts" / "check-publish-paths.sh"
        self.assertTrue(sweep.is_file(),
                        "scripts/check-publish-paths.sh must exist: it is what "
                        "stops a second publish path surviving on another ref")
        self.assertIn("scripts/check-publish-paths.sh", self.text,
                      "build-candidate.yml must run the publish-path sweep")


@unittest.skipIf(yaml is None, "PyYAML not installed; workflow lint skipped")
class LeastAuthorityTests(unittest.TestCase):
    """CT-83: the repository write grant exists only where the write happens.

    A candidate dispatch builds bytes and stops, so it must not carry
    `contents: write` anywhere. A publish dispatch must carry it only on the job
    that creates the release. Each job's own `if:` is rendered with the M1
    harness instead of pattern-matched, so a job that merely starts gated — or
    whose condition is later widened — fails here rather than at release time.
    """

    @classmethod
    def setUpClass(cls):
        cls.data = yaml.safe_load(ACTIVE.read_text(encoding="utf-8"))
        cls.jobs = cls.data["jobs"]

    def effective_contents(self, job: dict) -> str:
        """The `contents` scope a job holds once it runs.

        A job-level `permissions:` block replaces the workflow default for every
        scope, so a scope the job does not list is `none` — which is why the
        default alone cannot make a job read-only.
        """
        if "permissions" in job:
            return job["permissions"].get("contents", "none")
        return self.data.get("permissions", {}).get("contents", "none")

    def running_jobs(self, publish: bool) -> dict[str, str]:
        context = {
            "inputs.publish": publish,
            "inputs.notarize": False,
            "github.ref": "refs/heads/main",
            "github.event_name": "workflow_dispatch",
        }
        return {
            name: self.effective_contents(job)
            for name, job in self.jobs.items()
            if evaluate_if(job.get("if", True), context)
        }

    def test_the_workflow_default_is_read_only(self):
        self.assertEqual(self.data.get("permissions"), {"contents": "read"},
                         "the default grant must be read-only; jobs opt in to more")

    def test_both_dispatch_kinds_reach_at_least_one_job(self):
        # Without this, the two grant assertions below could pass by selecting
        # an empty set of jobs.
        for publish in (False, True):
            with self.subTest(publish=publish):
                self.assertTrue(self.running_jobs(publish),
                                "the render selected no job at all")

    def test_a_candidate_dispatch_holds_no_write_grant(self):
        writers = {name for name, scope in self.running_jobs(False).items()
                   if scope == "write"}
        self.assertEqual(
            writers, set(),
            "a publish=false dispatch must not hold contents: write anywhere",
        )

    def test_a_publish_dispatch_holds_the_write_grant_only_to_publish(self):
        running = self.running_jobs(True)
        writers = {name for name, scope in running.items() if scope == "write"}
        self.assertEqual(
            writers, {"release"},
            "publishing is the only act that needs to write to the repository",
        )
        self.assertNotIn("candidate-manifest", running,
                         "the candidate job must not run on a publish dispatch")
        release_runs = "\n".join(step.get("run", "")
                                 for step in self.jobs["release"]["steps"])
        self.assertIn("gh release create", release_runs,
                      "the job that holds the write grant is the one that publishes")


class PythonInterpreterPinTests(unittest.TestCase):
    """CT-55: the interpreter must be one full patch, and the same one everywhere.

    `python-version: "3.12"` is not a pin. setup-python resolves a bare minor to
    whatever that runner's tool cache already holds, so the 2026-10-06 candidate
    run (37486264639) built ONE commit on three different interpreters from one
    `python-version: "3.12"`:

        Windows x64 bundle      CPython 3.12.10
        Apple Silicon DMG       CPython 3.12.10
        Source archive and tests CPython 3.12.14
        Linux x86_64 AppImage   CPython 3.12.15

    That is CT-17's floating-runner-image problem one layer down, and it is the
    audit's "3.12.10 vs 3.12.14" example made literal.

    The pinned value is 3.12.10 because it is the newest CPython 3.12 that
    actions/python-versions still ships for linux-x64, win32-x64 AND
    darwin-arm64. From 3.12.11 onward those releases carry Linux assets only,
    so pinning a newer patch would not install on the Windows or macOS jobs at
    all — the 2026-10-06 run proves those two runners resolve a bare minor to
    3.12.10 from their tool cache and have no newer build available to them.

    This class deliberately does not import PyYAML. A release-path pin that
    goes green by being skipped is not a pin.
    """

    PINNED = "3.12.10"

    @staticmethod
    def _sites() -> dict[str, list[str]]:
        found: dict[str, list[str]] = {}
        for recipe in all_workflows():
            text = recipe.read_text(encoding="utf-8")
            values = re.findall(r'python-version:\s*["\']?([^"\'\s#]+)', text)
            if values:
                found[recipe.name] = values
        return found

    def test_every_interpreter_site_names_one_full_patch(self):
        """Every site is `x.y.z`. A bare minor, or `3.x`, is the float itself."""
        sites = self._sites()
        self.assertTrue(sites, "no python-version site found at all; the pin is gone")
        for name, values in sites.items():
            for value in values:
                with self.subTest(workflow=name, value=value):
                    self.assertRegex(
                        value, r"^\d+\.\d+\.\d+$",
                        f"{name}: python-version {value!r} is not a full x.y.z "
                        f"pin; setup-python would float it to the runner's tool "
                        f"cache",
                    )

    def test_every_interpreter_site_is_the_same_pin(self):
        """One interpreter for every job. Drift between jobs is the finding."""
        sites = self._sites()
        self.assertTrue(sites, "no python-version site found at all; the pin is gone")
        for name, values in sites.items():
            for value in values:
                with self.subTest(workflow=name, value=value):
                    self.assertEqual(
                        value, self.PINNED,
                        f"{name}: python-version {value!r} is not the pinned "
                        f"{self.PINNED}; every site must agree so one commit "
                        f"builds on one interpreter",
                    )

    def test_the_pin_is_one_that_every_runner_can_install(self):
        """The pin is 3.12.10 on purpose, not by accident of a local venv.

        3.12.11 and later actions/python-versions releases carry Linux assets
        only, so a pin chosen from "whatever my laptop runs" would break the
        Windows and macOS jobs. This asserts the value so changing it is a
        deliberate edit to this constant, with the reason above to argue with.
        """
        self.assertEqual(self.PINNED, "3.12.10",
                         "the pinned interpreter moved; re-check that "
                         "actions/python-versions still ships it for linux-x64, "
                         "win32-x64 and darwin-arm64 before accepting the change")
        self.assertTrue(self._sites(), "no python-version site found at all")

    def test_the_docs_and_build_scripts_name_the_exact_patch(self):
        """The next agent reads AGENTS.md and the build scripts, not the YAML.

        A pin nobody is told about gets "helpfully" bumped. These are the three
        places that currently tell an editor what the workflow does; if they
        name a bare minor or a different patch they are lying, which is itself
        a finding under the project's own rule.
        """
        guide = (ROOT / "AGENTS.md").read_text(encoding="utf-8")
        self.assertIn(f"**{self.PINNED}**", guide,
                      "AGENTS.md must name the exact pinned patch; "
                      "'both workflow jobs pin 3.12' both miscounted and "
                      "left the patch floating")
        for script in ("build-macos.sh", "build-windows.ps1"):
            text = (ROOT / "scripts" / script).read_text(encoding="utf-8")
            with self.subTest(script=script):
                self.assertRegex(
                    text,
                    rf"pins {re.escape(self.PINNED)} already",
                    f"{script} must tell an operator which patch the workflow "
                    f"pins, not just '3.12'",
                )
        dependency = (ROOT / "HWI-DEPENDENCY.md").read_text(encoding="utf-8")
        self.assertIn(self.PINNED, dependency,
                      "HWI-DEPENDENCY.md is the canonical Python record and "
                      "must name the pinned patch")



class BuildRecipeLookupTests(unittest.TestCase):
    """The pin tests must read a recipe from the source archive too.

    The 0.6.6 source-archive job caught PipToolsPinTests opening only
    .github/workflows/ while the tarball ships the same recipes under ci/.
    ToolchainPinTests then repeated the mistake and the 0.6.7 candidate caught
    it again. Both now go through support.find_build_recipe; this pins the
    helper so a third repeat has to break a test first.
    """

    def test_a_recipe_shipped_only_under_ci_is_found(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = pathlib.Path(tmp)
            (root / "ci").mkdir()
            recipe = root / "ci" / "windows-inputs.yml"
            recipe.write_text("name: archived\n", encoding="utf-8", newline="\n")
            self.assertEqual(find_build_recipe(root, "windows-inputs.yml"), recipe)

    def test_the_checkout_layout_still_wins(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = pathlib.Path(tmp)
            (root / ".github" / "workflows").mkdir(parents=True)
            (root / "ci").mkdir()
            canonical = root / ".github" / "workflows" / "windows-inputs.yml"
            canonical.write_text("name: checkout\n", encoding="utf-8", newline="\n")
            (root / "ci" / "windows-inputs.yml").write_text(
                "name: stale\n", encoding="utf-8", newline="\n")
            self.assertEqual(find_build_recipe(root, "windows-inputs.yml"), canonical)

    def test_a_recipe_in_neither_place_is_reported_missing_not_raised(self):
        with tempfile.TemporaryDirectory() as tmp:
            self.assertIsNone(find_build_recipe(pathlib.Path(tmp), "windows-inputs.yml"))


class ToolchainPinTests(unittest.TestCase):
    """CT-57: the tool that writes the locks must itself be hash-locked.

    pip-tools decides what every released build installs. It was fetched with a
    bare `pip install pip-tools==7.6.1` — a version pin with no artifact pin —
    and build-linux.sh separately ran `pip install --upgrade pip`, which is an
    unpinned fetch of the installer itself. Neither macOS nor Windows did that.
    """

    def setUp(self):
        self.lock = ROOT / "requirements-piptools.lock"
        self.lock_text = self.lock.read_text(encoding="utf-8") if self.lock.is_file() else ""

    def test_the_inputs_workflows_install_piptools_from_a_hash_lock(self):
        self.assertTrue(self.lock.is_file(),
                        "requirements-piptools.lock is missing; pip-tools would "
                        "be installed unpinned")
        for name in ("windows-inputs.yml", "linux-inputs.yml"):
            recipe = find_build_recipe(ROOT, name)
            self.assertIsNotNone(
                recipe, f"{name} is missing from both .github/workflows/ and ci/")
            text = recipe.read_text(encoding="utf-8")
            with self.subTest(workflow=name):
                active = "\n".join(
                    line for line in text.splitlines()
                    if not line.lstrip().startswith("#"))
                self.assertIn("--require-hashes", active,
                              f"{name} must install pip-tools under --require-hashes")
                self.assertIn("requirements-piptools.lock", active,
                              f"{name} must install pip-tools from the committed lock")
                self.assertNotRegex(
                    active, r"pip install[^\n]*pip-tools==",
                    f"{name} installs pip-tools by version alone, with no "
                    f"artifact hash — the one unverified fetch that decides "
                    f"what the release builds on",
                )

    def test_the_piptools_lock_pins_the_tool_by_hash(self):
        """Every pinned package carries a digest, not merely the headline one.

        The first version of this test asserted one hash for pip-tools and left
        it at that. A break-and-watch that deleted one of pip-tools' two wheel
        hashes stayed green — correctly, because one hash is still a pin — but
        the same shape of break against build, click or pyproject-hooks would
        have sailed through entirely. Every name==version line must be followed
        by at least one --hash=sha256: before the next one.
        """
        self.assertIn("pip-tools==7.6.1", self.lock_text)
        entries = re.split(r"\n(?=[A-Za-z0-9_.-]+==)", self.lock_text)
        pinned = [entry for entry in entries if re.match(r"[A-Za-z0-9_.-]+==", entry)]
        self.assertGreaterEqual(len(pinned), 4,
                                "the lock resolved almost nothing; it is not "
                                "a lock of pip-tools' dependency set")
        for entry in pinned:
            name = re.match(r"([A-Za-z0-9_.-]+==[^\s\\]+)", entry).group(1)
            with self.subTest(package=name):
                self.assertRegex(
                    entry, r"--hash=sha256:[0-9a-f]{64}",
                    f"{name} is pinned by version alone; --require-hashes would "
                    f"reject the file, and a hand-edited one must not weaken it",
                )
        for package in ("build==", "click==", "pyproject-hooks=="):
            self.assertIn(package, self.lock_text,
                          f"the lock is missing transitive dependency {package}")

    def test_no_build_script_upgrades_pip_unpinned(self):
        """`pip install --upgrade pip` is an unverified fetch of the installer.

        It lived only in build-linux.sh, so the three platforms disagreed about
        what installed their hash-locked trees.
        """
        for script in ("build-macos.sh", "build-linux.sh", "build-windows.ps1"):
            text = (ROOT / "scripts" / script).read_text(encoding="utf-8")
            active = "\n".join(
                line for line in text.splitlines()
                if not line.lstrip().startswith("#"))
            with self.subTest(script=script):
                self.assertNotRegex(
                    active, r"pip install[^\n]*--upgrade[^\n]*\bpip\b",
                    f"{script} upgrades pip from PyPI with no pin",
                )

    def test_the_source_archive_ships_the_piptools_lock(self):
        """The inputs recipes run from a checkout, but the archive must be able
        to reproduce them; a lock the tarball omits is a lock a reader cannot
        verify the recipes against."""
        script = (ROOT / "scripts" / "build-source.sh").read_text(encoding="utf-8")
        self.assertIn("requirements-piptools.lock", script,
                      "the source archive must ship requirements-piptools.lock")
        self.assertIn("requirements-piptools.txt", script,
                      "the source archive must ship the lock's input file")

    # CT-87: the two inputs that shape the AppImage but cannot be pinned the way
    # the Python tree is. The container is pinned by digest; the OS packages are
    # accepted floating inputs, recorded in the SBOM and named in the ledger.
    CONTAINER = "ubuntu:24.04"
    CONTAINER_DIGEST = (
        "sha256:534baea6a22c03a63003dbc8dbe78fe34bc0d7e595d9a9dc9834884ff530eb55"
    )

    def _active_recipe(self, name: str) -> str:
        recipe = find_build_recipe(ROOT, name)
        self.assertIsNotNone(
            recipe, f"{name} is missing from both .github/workflows/ and ci/")
        return "\n".join(
            line for line in recipe.read_text(encoding="utf-8").splitlines()
            if not line.lstrip().startswith("#"))

    def test_the_container_proof_runs_a_digest_not_a_moving_tag(self):
        """CT-87: a tag is a moving pointer; the proof must name bytes.

        `ubuntu:24.04` is republished as the image is rebuilt, so a run against
        the tag proves something about whatever it meant that day. Pinning the
        manifest-list digest makes the proof reproducible, and the refresh
        command sits beside the pin so the next reader can move it deliberately.
        """
        active = self._active_recipe("build-candidate.yml")
        self.assertIn(
            f"{self.CONTAINER}@{self.CONTAINER_DIGEST}", active,
            "the container proof must run a digest, not a tag")
        floating = re.findall(rf"{re.escape(self.CONTAINER)}(?![@\w])", active)
        self.assertEqual(
            floating, [],
            "the container is referenced by tag; pin the manifest digest with "
            "docker buildx imagetools inspect ubuntu:24.04 "
            "--format '{{.Manifest.Digest}}'",
        )
        recipe = find_build_recipe(ROOT, "build-candidate.yml")
        self.assertIn(
            "imagetools inspect", recipe.read_text(encoding="utf-8"),
            "the recipe must record, in a comment beside the pin, how to "
            "refresh the digest deliberately")

    def test_the_runner_packages_are_the_ones_the_build_script_declares(self):
        """CT-87: one list, declared once and recorded.

        Two lists that merely look alike drift. The workflow installs exactly
        the names scripts/build-linux.sh declares, and the SBOM records the
        version each one resolved to, so the AppImage's build inputs are
        readable even though they are not pinned.
        """
        script = (ROOT / "scripts" / "build-linux.sh").read_text(encoding="utf-8")
        declared = re.search(r"SYSTEM_PACKAGES=\(([^)]*)\)", script)
        self.assertIsNotNone(
            declared, "build-linux.sh must declare SYSTEM_PACKAGES once")
        names = sorted(declared.group(1).split())
        self.assertGreaterEqual(len(names), 3)

        active = self._active_recipe("build-candidate.yml")
        installs = []
        lines = active.splitlines()
        for index, line in enumerate(lines):
            if not re.search(
                    r"apt-get install\s+-y\s+--no-install-recommends", line):
                continue
            words = []
            while index < len(lines):
                text = lines[index]
                words.extend(word for word in text.split() if word != "\\")
                if not text.rstrip().endswith("\\"):
                    break
                index += 1
            marker = words.index("--no-install-recommends")
            installs.append(sorted(words[marker + 1:]))
        self.assertEqual(
            len(installs), 1,
            "expected exactly one runner apt install to compare against")
        self.assertEqual(
            installs[0], names,
            "the workflow installs a different set from the one "
            "scripts/build-linux.sh records in the SBOM")

    def test_every_floating_input_is_written_down(self):
        """CT-87: declining a pin is a decision that has to be visible.

        The runner's packages and the container's come from moving archives, so
        they are accepted floating inputs rather than pins. That is allowed only
        if the ledger says so: the sites, the digest, and what is recorded
        instead.
        """
        ledger = ROOT / "releases" / "PATCH-0.6.8.md"
        self.assertTrue(ledger.is_file(), "releases/PATCH-0.6.8.md is missing")
        text = ledger.read_text(encoding="utf-8")
        self.assertIn("Accepted floating inputs", text)
        self.assertIn(self.CONTAINER_DIGEST, text)
        for package in ("squashfs-tools", "librsvg2-bin", "build-essential",
                        "fuse3", "ca-certificates"):
            with self.subTest(package=package):
                self.assertIn(
                    package, text,
                    f"the ledger must name the floating package {package}")


class PublishPathSweepTests(unittest.TestCase):
    """CT-48: a second publish path must not survive on any ref.

    WorkflowConfigTests.test_no_second_publish_path_exists looks only at the
    local checkout. That blind spot is the whole reason build-windows.yml
    stayed live and dispatchable on windows-port across two audit cycles while
    the pipeline comment claimed no second path existed. These tests drive
    scripts/check-publish-paths.sh against a fixture remote so the sweep
    itself is pinned to fail when a branch can publish.

    Deliberately NOT gated on PyYAML: the sweep is bash + git and must run in
    every environment, including the Windows job.
    """

    def _repo(self, folder: pathlib.Path) -> None:
        def git(*args: str) -> None:
            subprocess.run(["git", *args], cwd=folder, check=True,
                           capture_output=True, text=True)
        git("init", "-q", "-b", "main")
        git("config", "user.name", "sweep-fixture")
        git("config", "user.email", "sweep-fixture@example.invalid")
        git("config", "commit.gpgsign", "false")

    def _write(self, folder: pathlib.Path, name: str, body: str) -> None:
        path = folder / ".github" / "workflows" / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8", newline="\n")

    def _commit(self, folder: pathlib.Path, message: str) -> None:
        subprocess.run(["git", "add", "-A"], cwd=folder, check=True,
                       capture_output=True, text=True)
        subprocess.run(["git", "commit", "-q", "-m", message], cwd=folder,
                       check=True, capture_output=True, text=True)

    def _branch(self, folder: pathlib.Path, name: str) -> None:
        subprocess.run(["git", "switch", "-q", "-c", name], cwd=folder,
                       check=True, capture_output=True, text=True)

    def _drop(self, folder: pathlib.Path, name: str) -> None:
        subprocess.run(["git", "branch", "-q", "-D", name], cwd=folder,
                       check=True, capture_output=True, text=True)

    def _tag(self, folder: pathlib.Path, name: str) -> None:
        subprocess.run(["git", "tag", name], cwd=folder,
                       check=True, capture_output=True, text=True)

    def _switch(self, folder: pathlib.Path, name: str) -> None:
        subprocess.run(["git", "switch", "-q", name], cwd=folder,
                       check=True, capture_output=True, text=True)

    def _run_sweep(self, folder: pathlib.Path):
        return run_bash_file(ROOT / "scripts" / "check-publish-paths.sh",
                             str(folder), cwd=folder, timeout=60)

    CLEAN = (
        "name: ok\n"
        "on: workflow_dispatch\n"
        "jobs:\n"
        "  build:\n"
        "    runs-on: ubuntu-24.04\n"
        "    permissions:\n"
        "      contents: read\n"
        "    steps:\n"
        "      - run: echo ok\n"
    )
    PUBLISHING = (
        "name: evil\n"
        "on: workflow_dispatch\n"
        "jobs:\n"
        "  build:\n"
        "    runs-on: ubuntu-24.04\n"
        "    permissions:\n"
        "      contents: write\n"
        "    steps:\n"
        "      - run: gh release create v9 \"$GITHUB_SHA\"\n"
    )
    SILENT_RETIRED = (
        "name: silent\n"
        "on: workflow_dispatch\n"
        "jobs:\n"
        "  build:\n"
        "    runs-on: ubuntu-24.04\n"
        "    steps:\n"
        "      - run: echo ok\n"
    )
    # The blanket grant. A denylist that only knew `contents: write` and
    # `gh release` missed this completely.
    PUBLISHING_WRITE_ALL = (
        "name: blanket\n"
        "on: workflow_dispatch\n"
        "jobs:\n"
        "  build:\n"
        "    runs-on: ubuntu-24.04\n"
        "    permissions: write-all\n"
        "    steps:\n"
        "      - run: echo ok\n"
    )
    # The REST path, with no CLI and no write grant of its own.
    PUBLISHING_REST = (
        "name: rest\n"
        "on: workflow_dispatch\n"
        "jobs:\n"
        "  build:\n"
        "    runs-on: ubuntu-24.04\n"
        "    steps:\n"
        "      - run: gh api -X POST /repos/$GITHUB_REPOSITORY/releases\n"
    )
    # A third-party release action.
    PUBLISHING_ACTION = (
        "name: action\n"
        "on: workflow_dispatch\n"
        "jobs:\n"
        "  build:\n"
        "    runs-on: ubuntu-24.04\n"
        "    steps:\n"
        "      - uses: softprops/action-gh-release@v2\n"
    )
    # A publisher that refuses every ref which is not main. This is what makes
    # a published tag inert rather than an offender.
    GUARDED = (
        "name: guarded\n"
        "on: workflow_dispatch\n"
        "jobs:\n"
        "  build:\n"
        "    runs-on: ubuntu-24.04\n"
        "    permissions:\n"
        "      contents: write\n"
        "    steps:\n"
        "      - run: |\n"
        "          if [ \"$GITHUB_REF\" != \"refs/heads/main\" ]; then\n"
        "            echo 'refusing'\n"
        "            exit 1\n"
        "          fi\n"
        "          gh release create v9 \"$GITHUB_SHA\"\n"
    )
    # Prose, not publication. This is the real shape of linux-inputs.yml and
    # windows-inputs.yml, whose comments used to spell the patterns.
    COMMENT_ONLY = (
        "name: prose\n"
        "on: workflow_dispatch\n"
        "jobs:\n"
        "  build:\n"
        "    runs-on: ubuntu-24.04\n"
        "    steps:\n"
        "      - run: echo ok\n"
        "# This recipe has no contents: write grant and never runs gh release.\n"
    )

    def test_the_sweep_refuses_a_remote_branch_carrying_a_release_job(self):
        """Refusal half: contents:write + gh release on a non-main branch."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "evil")
            self._write(repo, "build-candidate.yml", self.PUBLISHING)
            self._commit(repo, "evil")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertNotEqual(result.returncode, 0,
                                f"the sweep accepted a publishing branch:\n{out}")
            self.assertIn("refusing: a non-main ref carries a publish-capable workflow",
                          out)
            self.assertIn("evil", out)
            self.assertIn("build-candidate.yml", out)
            # The specific reason, not just the refusal. This fixture carries
            # both markers, so without this a broken contents:write matcher
            # hides behind the gh-release half and the test stays green.
            self.assertIn("grants-contents-write", out)

    def test_the_sweep_refuses_a_branch_that_only_runs_gh_release(self):
        """Refusal half, second marker: `gh release` without contents:write.

        The two markers are independent. A recipe that uploads through a
        token rather than the workflow's own GITHUB_TOKEN grants no
        contents:write and must still be refused.
        """
        sneaky = (
            "name: sneaky\n"
            "on: workflow_dispatch\n"
            "jobs:\n"
            "  build:\n"
            "    runs-on: ubuntu-24.04\n"
            "    permissions:\n"
            "      contents: read\n"
            "    steps:\n"
            "      - run: gh release upload v9 ./dist/*\n"
        )
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "sneaky")
            self._write(repo, "build-candidate.yml", sneaky)
            self._commit(repo, "sneaky")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertNotEqual(result.returncode, 0,
                                f"the sweep accepted a gh-release branch:\n{out}")
            self.assertIn("refusing: a non-main ref carries a publish-capable workflow", out)
            self.assertIn("runs-gh-release", out)

    def test_the_sweep_refuses_the_retired_per_platform_workflow_names(self):
        """Refusal half: the file NAME is enough, even with no markers.

        A rewrite that strips the release job but keeps the file is still a
        retired publisher and must not exist on any ref.
        """
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "windows-port")
            self._write(repo, "build-windows.yml", self.SILENT_RETIRED)
            self._commit(repo, "windows-port")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertNotEqual(result.returncode, 0,
                                f"the sweep accepted build-windows.yml:\n{out}")
            self.assertIn("refusing: a non-main ref carries a publish-capable workflow",
                          out)
            self.assertIn("windows-port", out)
            self.assertIn("build-windows.yml", out)
            self.assertIn("retired-per-platform-publisher", out)

    def test_the_sweep_accepts_a_repo_whose_only_publisher_is_main(self):
        """Positive half: main may publish; a clean sibling branch is fine."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.PUBLISHING)
            self._commit(repo, "main")
            self._branch(repo, "feature")
            # The sibling inherits main's tree, so replace the publisher with a
            # recipe that cannot publish and add the lock-only inputs recipe —
            # the real shape of a cleaned non-main branch.
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._write(repo, "windows-inputs.yml", self.SILENT_RETIRED)
            self._commit(repo, "feature")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertEqual(result.returncode, 0,
                             f"the sweep refused a clean repo:\n{out}")
            self.assertNotIn("refusing:", out)
            self.assertIn("ok: no non-main ref carries a publish-capable workflow", out)

    def test_the_sweep_forgets_a_branch_that_was_deleted_on_the_remote(self):
        """A ghost ref left over from a previous fetch is a false accusation."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "evil")
            self._write(repo, "build-candidate.yml", self.PUBLISHING)
            self._commit(repo, "evil")

            self.assertNotEqual(self._run_sweep(repo).returncode, 0)

            subprocess.run(["git", "switch", "-q", "main"], cwd=repo,
                           check=True, capture_output=True, text=True)
            self._drop(repo, "evil")
            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertEqual(result.returncode, 0,
                             f"the sweep still blamed a deleted branch:\n{out}")

    def test_the_sweep_enumerates_remote_heads_not_only_the_checkout(self):
        """Body pin: the blind spot was scanning the working tree.

        If this script is rewritten to glob('.github/workflows') it goes green
        on a repo whose evil lives entirely on another ref — the exact CT-48
        failure. Both the private ref namespace and the fetch must stay.
        """
        text = (ROOT / "scripts" / "check-publish-paths.sh").read_text(encoding="utf-8")
        self.assertIn("refs/heads/*", text,
                      "the sweep must fetch every remote head, not just this checkout")
        self.assertIn("git fetch", text)
        self.assertIn("git for-each-ref", text)
        self.assertIn("refs/remotes/publish-audit", text)
        self.assertIn("git ls-tree", text)

    def test_the_sweep_shouts_its_refusal_to_stderr(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "evil")
            self._write(repo, "build-candidate.yml", self.PUBLISHING)
            self._commit(repo, "evil")

            result = self._run_sweep(repo)
            self.assertIn("refusing: a non-main ref carries a publish-capable workflow",
                          result.stderr)
            self.assertEqual(result.returncode, 1)

    def test_the_sweep_reads_a_quoted_write_permission(self):
        """`contents: "write"` is how a template renders it."""
        quoted = (
            "name: quoted\n"
            "on: workflow_dispatch\n"
            "jobs:\n"
            "  build:\n"
            "    runs-on: ubuntu-24.04\n"
            "    permissions:\n"
            "      contents: \"write\"\n"
            "    steps:\n"
            "      - run: echo ok\n"
        )
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "quoted")
            self._write(repo, "build-candidate.yml", quoted)
            self._commit(repo, "quoted")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertNotEqual(result.returncode, 0,
                                f"the sweep accepted a quoted write grant:\n{out}")
            self.assertIn("grants-contents-write", out)

    def test_the_sweep_reads_a_body_regardless_of_case(self):
        """The matcher is nocasematch, as the grep -i it replaced was."""
        shouty = (
            "name: shouty\n"
            "on: workflow_dispatch\n"
            "jobs:\n"
            "  build:\n"
            "    runs-on: ubuntu-24.04\n"
            "    permissions:\n"
            "      CONTENTS: WRITE\n"
            "    steps:\n"
            "      - run: echo ok\n"
        )
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "shouty")
            self._write(repo, "build-candidate.yml", shouty)
            self._commit(repo, "shouty")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertNotEqual(result.returncode, 0,
                                f"the sweep missed a body it should read:\n{out}")
            self.assertIn("grants-contents-write", out)

    # -- W2: the allowlist, the wider matchers, and the tags ------------------
    #
    # CT-76/CT-77: the sweep fetched `+refs/heads/*` only, so 46 published
    # tags that freeze an UNGUARDED publisher were invisible, and its two
    # hard-coded patterns (`contents: write`, the substring `gh release`) never
    # saw `permissions: write-all`, a REST release POST, or any of the
    # third-party release actions. These tests drive the real script against a
    # fixture remote for each form the audit demonstrated.

    def _repo_with_tag(self, repo: pathlib.Path, tag: str, body: str) -> None:
        """main clean, a `release` branch carrying `body`, tagged, branch gone.

        The branch is deleted afterwards so the tag is the only ref under
        test; otherwise a red result could come from the branch half and the
        tag half could still be blind.
        """
        self._repo(repo)
        self._write(repo, "build-candidate.yml", self.CLEAN)
        self._commit(repo, "main")
        self._branch(repo, "release")
        self._write(repo, "build-candidate.yml", body)
        self._commit(repo, "release")
        self._tag(repo, tag)
        self._switch(repo, "main")
        self._drop(repo, "release")

    def test_the_sweep_refuses_a_tag_carrying_an_unguarded_publisher(self):
        """The tag half of CT-76, on a tag that is not on the legacy list.

        This is the audit's own fixture, inverted: a tag whose publisher has
        no default-branch guard used to pass silently. A NEW tag may not
        reintroduce one, which is what keeps the rule closed under change.
        """
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo_with_tag(repo, "v9.9.9", self.PUBLISHING)

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertNotEqual(result.returncode, 0,
                                f"the sweep accepted a tag that can publish:\n{out}")
            self.assertIn("unguarded-tag-publisher", out)
            self.assertIn("v9.9.9", out)

    def test_the_sweep_accepts_an_enumerated_legacy_tag(self):
        """The 46 tags published before the guard existed are a known residual.

        They are immutable (AGENTS.md forbids deleting or moving a published
        tag), so the sweep records them instead of blocking every release
        forever. The name is taken from the script's own list, so this test
        stays honest if that list is edited.
        """
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo_with_tag(repo, "v0.4.0", self.PUBLISHING)

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertEqual(result.returncode, 0,
                             f"the sweep refused an enumerated legacy tag:\n{out}")
            self.assertIn("legacy-unguarded-tag-publisher", out)

    def test_the_sweep_accepts_a_tag_whose_publisher_refuses_off_main(self):
        """A guarded publisher cannot publish from a tag ref, so it is inert."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo_with_tag(repo, "v9.9.8", self.GUARDED)

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertEqual(result.returncode, 0,
                             f"the sweep refused a guarded tag publisher:\n{out}")
            self.assertIn("guarded-tag-publisher", out)

    def test_the_sweep_refuses_a_branch_granting_write_all(self):
        """CT-77: `permissions: write-all` is a blanket grant the old
        denylist never spelled."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "blanket")
            self._write(repo, "build-candidate.yml", self.PUBLISHING_WRITE_ALL)
            self._commit(repo, "blanket")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertNotEqual(result.returncode, 0,
                                f"the sweep accepted write-all:\n{out}")
            self.assertIn("grants-write-all", out)

    def test_the_sweep_refuses_a_branch_that_posts_to_the_rest_api(self):
        """`gh api -X POST …/releases` publishes without the release CLI."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "rest")
            self._write(repo, "build-candidate.yml", self.PUBLISHING_REST)
            self._commit(repo, "rest")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertNotEqual(result.returncode, 0,
                                f"the sweep accepted a REST publish:\n{out}")
            self.assertIn("names-release-surface", out)

    def test_the_sweep_refuses_a_branch_using_a_release_action(self):
        """Every `*-action-gh-release` variant names the release surface."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "action")
            self._write(repo, "build-candidate.yml", self.PUBLISHING_ACTION)
            self._commit(repo, "action")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertNotEqual(result.returncode, 0,
                                f"the sweep accepted a release action:\n{out}")
            self.assertIn("names-release-surface", out)

    def test_the_sweep_ignores_a_workflow_whose_only_match_is_a_comment(self):
        """The honest `linux-inputs.yml` shape must not be an offender.

        Its comment used to spell both patterns, which made a lock-only recipe
        look like a publisher — and one copy of that comment is frozen in the
        immutable tag v0.6.7, where it could never be fixed.
        """
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "inputs")
            self._write(repo, "linux-inputs.yml", self.COMMENT_ONLY)
            self._commit(repo, "inputs")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertEqual(result.returncode, 0,
                             f"the sweep refused a comment-only recipe:\n{out}")

    def test_the_sweep_still_flags_a_pattern_after_a_hash_on_a_code_line(self):
        """Documented residual, pinned so it cannot be softened by accident.

        Only a line whose FIRST non-whitespace character is `#` is skipped. No
        line is ever truncated at a `#`, so `run: echo ok # gh release` is
        still matched whole. That is the fail-closed direction: the cost is a
        false positive on a trailing comment, never a false negative hidden
        behind a quote.
        """
        trailing = (
            "name: trailing\n"
            "on: workflow_dispatch\n"
            "jobs:\n"
            "  build:\n"
            "    runs-on: ubuntu-24.04\n"
            "    steps:\n"
            "      - run: echo ok  # this prose mentions gh release\n"
        )
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.CLEAN)
            self._commit(repo, "main")
            self._branch(repo, "trailing")
            self._write(repo, "build-candidate.yml", trailing)
            self._commit(repo, "trailing")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertNotEqual(result.returncode, 0,
                                f"a pattern after a # on a code line went unseen:\n{out}")
            self.assertIn("runs-gh-release", out)

    def test_the_sweep_refuses_a_second_publisher_on_main(self):
        """main may carry exactly one publisher, and it must be by name.

        The old rule skipped main entirely, so any number of publishers could
        sit there as long as one of them was the published path.
        """
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.PUBLISHING)
            self._commit(repo, "main")
            self._write(repo, "windows-inputs.yml", self.PUBLISHING)
            self._commit(repo, "second publisher on main")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertNotEqual(result.returncode, 0,
                                f"the sweep accepted two publishers on main:\n{out}")
            self.assertIn("second-publisher-on-main", out)
            self.assertIn("windows-inputs.yml", out)

    def test_the_sweep_accepts_main_publishing_through_the_one_named_file(self):
        """Positive half: build-candidate.yml on main still passes."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp)
            self._repo(repo)
            self._write(repo, "build-candidate.yml", self.PUBLISHING)
            self._write(repo, "linux-inputs.yml", self.CLEAN)
            self._commit(repo, "main")

            result = self._run_sweep(repo)
            out = result.stdout + result.stderr
            self.assertEqual(result.returncode, 0,
                             f"the sweep refused the documented publish path:\n{out}")
            self.assertIn("ok: no non-main ref carries a publish-capable workflow", out)

    def test_the_sweep_fetches_tags_into_their_own_namespace(self):
        """Body pin: tags are fetched explicitly, and never as heads.

        If the tag refspec is dropped the tag tests go blind again; if the two
        namespaces overlap, a tag would be judged by the head rule (allowed by
        name) and an unguarded tag would pass.
        """
        text = (ROOT / "scripts" / "check-publish-paths.sh").read_text(encoding="utf-8")
        self.assertIn("refs/tags/*", text,
                      "the sweep must fetch every remote tag, not just heads")
        self.assertIn("refs/remotes/publish-audit/tags", text)
        self.assertIn("refs/remotes/publish-audit/heads", text)


class SweepFailClosedPins(unittest.TestCase):
    """The sweep must never turn a failure to read into "ok".

    That is exactly what happened on the Windows job: `git show ref:path
    2>/dev/null || true` returned nothing, both body checks found nothing to
    match, and a branch that publishes was reported clean. Four behavioural
    tests went red there and stayed green on Mac and Linux. These pins hold the
    half the behaviour cannot easily reach: an unreadable body is an offender,
    and no external matcher is involved whose absence could go silent.
    """

    @classmethod
    def setUpClass(cls):
        cls.text = (ROOT / "scripts" / "check-publish-paths.sh").read_text(
            encoding="utf-8")

    def test_an_unreadable_workflow_body_is_an_offender(self):
        self.assertIn("unreadable-workflow", self.text,
                      "a body the sweep cannot read must be reported, not passed")
        self.assertIn('report "$label" "$path" "unreadable-workflow"', self.text)

    def test_the_body_read_is_not_allowed_to_swallow_its_failure(self):
        reads = [line for line in self.text.splitlines()
                 if "cat-file blob" in line and "body=" in line]
        self.assertTrue(reads, "the sweep must read each workflow body with git cat-file")
        for line in reads:
            self.assertNotIn("|| true", line,
                             "the body read must fail loudly: " + line)
            self.assertIn("if !", line,
                          "the body read must be gated on its own success: " + line)

    def test_the_sweep_matches_bodies_with_bash_and_not_with_grep(self):
        """grep is an external tool. When it is missing or broken, a pipeline
        that ends in grep silently reports "no match" — a refusal becomes a
        pass. Bash's own [[ ]] cannot do that."""
        code = "\n".join(line for line in self.text.splitlines()
                         if not line.lstrip().startswith("#"))
        self.assertNotRegex(code, r"(^|[\s|;&])grep(\s|$)",
                            "the sweep must not depend on grep to decide a refusal")
        self.assertIn("nocasematch", self.text)
        self.assertIn("CONTENT_WRITE_RE", self.text)

    def test_the_bodies_come_from_object_ids_not_from_rev_colon_path(self):
        """`git show ref:path` is the read that went blind on Windows.

        An object id from ls-tree has no path syntax for anything to mangle.
        """
        self.assertIn("git cat-file blob", self.text)
        self.assertIn("git ls-tree -r", self.text)
        self.assertNotIn('git show "${ref}:${path}"', self.text)


class GuardBodyPins(unittest.TestCase):
    """CT-52: a guard is only a guard if its body can fail.

    The old pins asserted the step NAMES existed. A step named "Refuse an
    unsigned public release" whose body is `true` passes every one of them.
    These assert the refusal itself is in the body.
    """

    @classmethod
    def setUpClass(cls):
        cls.text = ACTIVE.read_text(encoding="utf-8")

    def _step_body(self, name: str) -> str:
        """The `run:` body of the step named `name`, and nothing else.

        A step ends at the next `- name:` (or at the next job key). The first
        version of this reached past the step into its neighbour, so deleting
        one guard's `exit 1` still left one in the captured text and the pin
        stayed green — the exact shape of a test that cannot fail.
        """
        lines = self.text.splitlines()
        marker = f"- name: {name}"
        start = None
        indent = None
        for index, line in enumerate(lines):
            if line.strip() == marker:
                start = index
                indent = len(line) - len(line.lstrip())
                break
        self.assertIsNotNone(start, f"no step named {name!r} in {ACTIVE}")

        body = []
        for line in lines[start + 1:]:
            stripped = line.strip()
            current_indent = len(line) - len(line.lstrip())
            if stripped.startswith("- name:") and current_indent <= indent:
                break
            if stripped and not line.startswith(" " * (indent + 1)):
                # Outdented to the step's own level or above: the step is over.
                if not stripped.startswith("- name:"):
                    break
            body.append(line)
        text = "\n".join(body)
        self.assertIn("run:", text,
                      f"{name} has no run: block; nothing for it to refuse with")
        return text

    def test_the_publish_sweep_gate_step_fails_closed_in_its_body(self):
        body = self._step_body("Refuse a second publish path on any ref")
        self.assertIn("scripts/check-publish-paths.sh", body)
        self.assertIn("exit 1", body,
                      "the gate must exit 1 itself when the sweep fails")
        self.assertIn(">&2", body, "the refusal must go to stderr")

    def test_every_named_guard_step_contains_its_own_refusal(self):
        for name, refusal in (
            ("Refuse an unsigned public release",
             "Publishing requires a signed and notarized build."),
            ("Require the default branch for publication",
             "Public releases must be dispatched from main."),
            ("Refuse a second publish path on any ref",
             "A non-main ref can publish."),
        ):
            body = self._step_body(name)
            self.assertIn("exit 1", body,
                          f"{name} must be able to fail; its body has no exit 1")
            self.assertIn(refusal, body,
                          f"{name} must name what it refused")
            self.assertIn(">&2", body,
                          f"{name} must send the refusal to stderr")


class ReleaseNotesTests(unittest.TestCase):
    """What a downloader reads must not describe the build as two different things.

    v0.4.12 was published saying it was "notarized by Apple" AND "Unsigned,
    unnotarized test build" on consecutive lines, because the template emitted a
    hardcoded unsigned line regardless of which mode had just been chosen. The
    release notes are the first thing anyone reads, and nobody re-reads them.

    Deliberately NOT gated on PyYAML: this renders the template with the shell that
    runs it in CI, so it needs nothing but bash.
    """

    @classmethod
    def setUpClass(cls):
        cls.text = ACTIVE.read_text(encoding="utf-8")

    def render(self, notarize: str) -> str:
        """Run the workflow's own notes block with one mode selected.

        The title is echoed alongside the notes so assertions can reach both.
        """
        # Keep the heredoc's own EOF terminator. Without it bash reads to the end of
        # input, so anything appended below - the title echo - becomes notes text.
        # The tag assignment is prepended because the split consumed it, and
        # release_title is built from it.
        body, _, _ = self.text.split('tag="v${VERSION}"', 1)[1].partition("          EOF")
        block = 'tag="v${VERSION}"\n' + body + "          EOF\n"
        script = block
        # Print instead of writing notes.md, and drop the YAML indentation.
        script = script.replace("cat > notes.md <<EOF", "cat <<EOF")
        script = "\n".join(line[10:] if line.startswith(" " * 10) else line
                           for line in script.splitlines())
        # NOTARIZE arrives through env: in the workflow, so the mode is selected
        # the same way the runner would select it (0.6.8 moved every expression
        # out of the script text; see CT-72).
        runner = ("VERSION=9.9.9 GITHUB_REF_NAME=main GITHUB_SHA=abcdef1234567890\n"
                  f"NOTARIZE={notarize}\n"
                  + script + '\necho "TITLE=${release_title}"\n')
        # Never bash -c: Windows CreateProcess quoting mangles multiline -c
        # scripts into an exit-1/empty-stderr failure. run_bash_script writes
        # LF-terminated text to a file and executes that.
        result = run_bash_script(runner, cwd=ROOT, timeout=60)
        self.assertEqual(result.returncode, 0, result.stderr)
        return result.stdout

    def title_of(self, notarize: str) -> str:
        for line in self.render(notarize).splitlines():
            if line.startswith("TITLE="):
                return line[len("TITLE="):]
        self.fail("the block did not set release_title")

    def test_the_title_is_the_version_and_nothing_else(self):
        """A release name is an identity, not a provenance record."""
        for mode in ("true", "false"):
            with self.subTest(notarize=mode):
                self.assertEqual(self.title_of(mode), "v9.9.9")

    def test_a_notarized_release_does_not_also_claim_to_be_unsigned(self):
        body = self.render("true")
        self.assertIn("notarized by Apple", body)
        self.assertNotIn("Unsigned", body)
        self.assertNotIn("unnotarized", body)

    def test_a_test_build_says_it_is_unsigned(self):
        body = self.render("false")
        self.assertIn("Unsigned", body)
        self.assertNotIn("notarized by Apple", body)

    def test_the_notes_offer_every_platform_and_its_verification(self):
        """One release page carries macOS, Windows, Linux and how to verify them."""
        body = self.render("true")
        self.assertIn("Bitcoin-Easy-Signer-v9.9.9-macOS.dmg", body)
        self.assertIn("Bitcoin-Easy-Signer-v9.9.9-windows-x64.zip", body)
        self.assertIn("Bitcoin-Easy-Signer-v9.9.9-linux-x86_64.AppImage", body)
        self.assertIn("bitcoin-easy-multisig-signer-v9.9.9.tar.gz", body)
        self.assertIn("SHA256SUMS.asc", body)
        self.assertIn("signing-key.asc", body)
        self.assertIn("Sigstore", body)
        self.assertIn("SIGNING.md", body)

    def test_the_notes_carry_no_stale_version_specific_boilerplate(self):
        """v0.4.12 shipped a paragraph about a Sparrow/Nunchuk change-path patch."""
        for mode in ("true", "false"):
            with self.subTest(notarize=mode):
                body = self.render(mode)
                self.assertNotIn("Sparrow", body)
                self.assertNotIn("Nunchuk", body)

    def test_the_heading_is_the_version_alone(self):
        """Build provenance is not a release name; it belongs in the notes body."""
        body = self.render("true")
        self.assertIn("## v9.9.9", body)
        self.assertNotIn("— Apple Silicon", body)
        self.assertNotIn("— notarized", body)
        self.assertNotIn("— unsigned", body)

    def test_the_notes_name_the_network_the_app_actually_opens_on(self):
        """The notes described the pre-0.6.0 opening screen.

        They said "Mutinynet is the opening network", which 0.6.1 makes false. The
        notes are generated by this workflow, so a release would have told every
        downloader to expect the opposite of what they get.
        """
        for mode in ("true", "false"):
            with self.subTest(notarize=mode):
                body = self.render(mode)
                self.assertNotIn("Mutinynet is the opening network", body)
                self.assertIn("Opens on Bitcoin mainnet", body)
                self.assertIn("Enter Developer Mode", body)
                self.assertIn("the app reopens on mainnet", body)


if __name__ == "__main__":
    unittest.main()
