"""Static checks on the GitHub Actions workflows.

A broken shell block in a workflow costs a full CI round trip to discover, and a
tag-pinned action or a hardcoded version is easy to reintroduce. These checks are
cheap and run in the normal test suite.

One pipeline — .github/workflows/build-candidate.yml — builds every platform from
one commit and is the only workflow allowed to publish. The retired per-platform
workflows (build-windows.yml, build-linux.yml) must never come back: a second
publish path is how unverified bytes once reached a tagged release.

Skipped when PyYAML is unavailable (it is deliberately NOT an application
dependency); CI installs it for the source job so the checks do run there.
"""

import pathlib
import re
import unittest

from support import bash_syntax_check, run_bash_script

try:
    import yaml
except ImportError:  # pragma: no cover - depends on the environment
    yaml = None

ROOT = pathlib.Path(__file__).resolve().parent.parent
# The checkout keeps the canonical workflow under .github; the source archive
# keeps the generated copy at ci/build-candidate.yml. Pick whichever exists so
# these checks also run against the archived source, which is where an
# incomplete archive shows up.
ACTIVE = ROOT / ".github/workflows/build-candidate.yml"
if not ACTIVE.is_file():
    ACTIVE = ROOT / "ci/build-candidate.yml"


def all_workflows() -> list[pathlib.Path]:
    """Every workflow recipe, from the checkout or the extracted archive."""
    folder = ROOT / ".github" / "workflows"
    if not folder.is_dir():
        folder = ROOT / "ci"
    return sorted(folder.glob("*.yml"))


@unittest.skipIf(yaml is None, "PyYAML not installed; workflow lint skipped")
class WorkflowConfigTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.text = ACTIVE.read_text(encoding="utf-8")
        cls.data = yaml.safe_load(cls.text)

    def test_the_workflow_has_exactly_one_source_of_truth(self):
        """One canonical workflow, and no committed duplicate of it.

        scripts/build-source.sh copies the workflow into the archive as
        ci/build-candidate.yml. Keeping a second committed copy meant two files
        that had to be kept byte-identical by hand; the archive copy is generated
        now, so a committed one is drift waiting to happen.
        """
        self.assertTrue(ACTIVE.is_file(), "no workflow recipe found")
        checkout = ROOT / ".github/workflows/build-candidate.yml"
        if checkout.is_file():
            self.assertFalse(
                (ROOT / "ci/build-candidate.yml").is_file(),
                "ci/build-candidate.yml is generated by scripts/build-source.sh "
                "and must not also be committed as a second source of truth",
            )

    def test_every_shell_block_parses(self):
        checked = 0
        for job, spec in self.data["jobs"].items():
            for index, step in enumerate(spec.get("steps", [])):
                script = step.get("run")
                if not script:
                    continue
                if step.get("shell") == "pwsh":
                    # PowerShell is not bash; the Windows runner executes it.
                    continue
                checked += 1
                result = bash_syntax_check(script)
                label = f"{job}/{step.get('name') or f'step {index}'}"
                self.assertEqual(result.returncode, 0,
                                 f"{label} has invalid shell:\n{result.stderr}")
        self.assertGreater(checked, 5, "expected to lint the workflow's shell blocks")

    def test_every_workflow_file_lints_and_pins_actions(self):
        """The inputs producers get the same scrutiny as the release pipeline."""
        recipes = all_workflows()
        self.assertGreaterEqual(len(recipes), 3,
                                "build-candidate plus the two inputs workflows")
        for recipe in recipes:
            text = recipe.read_text(encoding="utf-8")
            data = yaml.safe_load(text)
            with self.subTest(workflow=recipe.name):
                for reference in re.findall(r"uses:\s*(\S+)", text):
                    self.assertRegex(
                        reference, r"^[\w.-]+/[\w.-]+@[0-9a-f]{40}$",
                        f"{recipe.name}: actions must be pinned to a full commit SHA")
                for job, spec in (data.get("jobs") or {}).items():
                    for step in spec.get("steps", []):
                        script = step.get("run")
                        if not script or step.get("shell") == "pwsh":
                            continue
                        result = bash_syntax_check(script)
                        self.assertEqual(
                            result.returncode, 0,
                            f"{recipe.name}/{job} has invalid shell:\n{result.stderr}")

    def test_actions_are_pinned_to_commit_shas(self):
        uses = re.findall(r"uses:\s*(\S+)", self.text)
        self.assertTrue(uses)
        for reference in uses:
            with self.subTest(action=reference):
                self.assertRegex(
                    reference, r"^[\w.-]+/[\w.-]+@[0-9a-f]{40}$",
                    "actions must be pinned to a full commit SHA, not a tag")

    def test_runner_images_are_pinned_not_floating(self):
        """CT-17: a `-latest` label silently changes the build environment.

        Every runs-on in every recipe must name a specific image. The release
        this closes was built on whatever `ubuntu-latest`/`windows-latest`
        happened to mean that week.
        """
        pinned = re.compile(
            r"runs-on:\s*(ubuntu-\d+\.\d+|windows-\d{4}|macos-\d+)\s*$")
        for recipe in all_workflows():
            text = recipe.read_text(encoding="utf-8")
            labels = [line.strip() for line in text.splitlines()
                      if line.strip().startswith("runs-on:")]
            self.assertTrue(labels, f"{recipe.name} has no runs-on to pin")
            for label in labels:
                with self.subTest(workflow=recipe.name, label=label):
                    self.assertNotIn("-latest", label,
                                     "runner images must not float on a -latest alias")
                    self.assertRegex(label, pinned)

    def test_no_version_number_is_hardcoded(self):
        # The version is read from version.py, so bumping it needs no workflow edit.
        self.assertNotRegex(self.text, r"\b0\.1\.\d+\b",
                            "the workflow must not hardcode a version")

    def test_release_is_not_tag_gated_and_not_a_prerelease(self):
        # The owner asked for a plain release, triggered by explicit dispatch.
        self.assertNotIn("--prerelease", self.text)
        self.assertNotIn("--clobber", self.text)
        release = self.data["jobs"]["release"]
        self.assertNotIn("if", release, "publishing must not be gated on a tag")
        self.assertEqual(release["permissions"], {"contents": "write"})

    def test_network_check_also_runs_without_ambient_trust(self):
        """Guards the check that caught the bundled-trust-store regression."""
        self.assertIn("SSL_CERT_DIR=/nonexistent/certs", self.text,
                      "CI must re-verify HTTPS with the host's CA configuration "
                      "removed, so only the bundled trust store can make it pass")

    def test_a_published_version_is_never_rebuilt(self):
        """Overwriting a published tag changes artifacts somebody already
        downloaded and verified. The publish step must refuse, not delete."""
        self.assertNotIn("gh release delete", self.text)
        self.assertIn('git ls-remote --exit-code --tags origin "refs/tags/$tag"', self.text)
        self.assertIn("Bump version.py", self.text)

    def test_release_checks_downloaded_bytes_before_any_publish(self):
        self.assertIn("shasum -a 256 -c SHA256SUMS", self.text)
        self.assertLess(self.text.index("shasum -a 256 -c SHA256SUMS"),
                        self.text.index("gh release create"))

    def test_dependency_installation_finishes_before_signing_material(self):
        self.assertNotIn("pip install --quiet", self.text)
        self.assertGreaterEqual(
            self.text.count("pip install --require-hashes -r requirements-ci.lock"), 3,
            "the source, macOS and Linux jobs all install the locked CI dependencies")
        self.assertNotIn("brew install", self.text)
        macos = self.data["jobs"]["macos"]["steps"]
        names = [step.get("name", "") for step in macos]
        signing = names.index("Import the Developer ID certificate")
        preparation = names.index("Prepare hash-locked build environment before signing secrets")
        self.assertLess(preparation, signing)
        self.assertIn("PREPARE_ONLY=1", macos[preparation]["run"])
        build_step = next(step for step in macos if step.get("name") == "Build the DMG")
        self.assertEqual(build_step["env"]["BUILD_DEPS_PREPARED"], "1")
        for step in macos[signing + 1:]:
            script = step.get("run", "")
            self.assertNotIn("pip install", script)
            self.assertNotIn("brew install", script)
        self.assertNotIn('echo "KEYCHAIN_PASSWORD=', self.text)

    def test_only_manual_dispatch_can_publish(self):
        """A source push must not publish a money-moving desktop app."""
        trigger = self.data.get("on", self.data.get(True))
        self.assertIn("workflow_dispatch", trigger)
        self.assertNotIn("push", trigger)
        inputs = trigger["workflow_dispatch"]["inputs"]
        self.assertIs(inputs["publish"]["default"], False)
        self.assertIn("Refuse an unsigned public release", self.text)
        self.assertIn("Refusing to publish an unsigned or unnotarized build", self.text)

    def test_publication_is_restricted_to_the_default_branch(self):
        guard = next(step for step in self.data["jobs"]["version"]["steps"]
                     if step.get("name") == "Require the default branch for publication")
        self.assertEqual(guard["if"], "${{ inputs.publish }}")
        self.assertIn('refs/heads/main', guard["run"])
        self.assertIn("candidate_run_id", guard["run"])

    def test_versioned_release_notes_are_included_when_present(self):
        self.assertIn('release_notes="releases/RELEASE-NOTES-${VERSION}.md"', self.text)
        self.assertIn('cat "$release_notes" >> notes.md', self.text)

    def test_publication_promotes_a_successful_notarized_candidate_from_same_commit(self):
        checksums = self.data["jobs"]["checksums"]
        self.assertIn("actions", checksums["permissions"])
        promote = next(step for step in checksums["steps"]
                       if step.get("name") == "Download and verify the tested candidate artifacts")
        self.assertEqual(promote["if"], "${{ inputs.publish }}")
        self.assertEqual(promote["env"]["GH_REPO"], "${{ github.repository }}")
        for required in (
                "gh api", "gh run download", "head_sha", "conclusion", "head_branch",
                '.path == ".github/workflows/build-candidate.yml"',
                "CANDIDATE-MANIFEST.txt", "notarize=true", "publish=false",
                "shasum -a 256 -c SHA256SUMS"):
            with self.subTest(required=required):
                self.assertIn(required, promote["run"])
        release = self.data["jobs"]["release"]
        download = next(step for step in release["steps"]
                        if step.get("uses", "").startswith("actions/download-artifact"))
        self.assertEqual(download["with"]["name"], "release-assets")
        verify = next(step for step in release["steps"]
                      if step.get("name") == "Verify downloaded release bytes")
        publish = next(step for step in release["steps"]
                       if step.get("name") == "Publish the release")
        self.assertLess(release["steps"].index(verify), release["steps"].index(publish))
        self.assertIn("CANDIDATE-MANIFEST.txt", self.text)

    def test_a_candidate_dispatch_builds_without_publishing(self):
        """Building and publishing are separate acts.

        Publishing is irreversible by policy: a published tag is never rebuilt. That
        made the first dispatch of a version the point of no return, so the only way
        to correct an artifact nobody had opened yet was to bump the version. The
        candidate path must leave before the release step creates anything, and
        an ordinary dispatch must stay nonpublishing.
        """
        trigger = self.data.get("on", self.data.get(True))
        inputs = trigger["workflow_dispatch"]["inputs"]
        self.assertIn("publish", inputs)
        self.assertIs(inputs["publish"]["default"], False,
                      "an ordinary dispatch must build only a candidate")
        self.assertIs(inputs["notarize"]["default"], False)
        guard = self.text.index('if [[ "${{ inputs.publish }}" != "true" ]]')
        notes = self.text.index("cat > notes.md <<EOF")
        publish = self.text.index("gh release create")
        self.assertLess(notes, guard, "the guard must run after the notes are built")
        self.assertLess(guard, publish, "the candidate path must exit before publishing")
        self.assertIn("was built and NOT published", self.text)
        # A candidate is not a draft release and not a prerelease: it creates no
        # release object at all, so there is nothing to publish by accident.
        self.assertNotIn("--draft", self.text)

    def test_one_pipeline_builds_every_platform_from_one_commit(self):
        """The three platform jobs share one run, one commit, one sums file."""
        jobs = self.data["jobs"]
        for job in ("version", "source", "macos", "windows", "linux",
                    "checksums", "release"):
            self.assertIn(job, jobs)
        self.assertEqual(jobs["checksums"]["needs"],
                         ["version", "source", "macos", "windows", "linux"])
        self.assertEqual(jobs["release"]["needs"],
                         ["version", "source", "macos", "windows", "linux", "checksums"])
        self.assertEqual(jobs["windows"]["runs-on"], "windows-2022")
        self.assertEqual(jobs["linux"]["runs-on"], "ubuntu-24.04")
        self.assertEqual(jobs["macos"]["runs-on"], "macos-15")

    def test_platform_artifacts_have_distinct_names_and_suffixed_sboms(self):
        self.assertIn("name: windows-bundle", self.text)
        self.assertIn("name: linux-desktop", self.text)
        self.assertIn("BUILD-SBOM-windows-x64.json", self.text)
        self.assertIn("BUILD-SBOM-linux-x86_64.json", self.text)
        for step_name in ("Download current Windows bundle for a nonpublishing candidate",
                          "Download current Linux assets for a nonpublishing candidate"):
            step = next(step for step in self.data["jobs"]["checksums"]["steps"]
                        if step.get("name") == step_name)
            self.assertEqual(step["if"], "${{ !inputs.publish }}")

    def test_the_publish_verification_counts_every_platform(self):
        promote = next(step for step in self.data["jobs"]["checksums"]["steps"]
                       if step.get("name") == "Download and verify the tested candidate artifacts")
        for required in (
                "-name '*.tar.gz' | wc -l | tr -d ' ')\" = 2",
                "-name '*.dmg' | wc -l | tr -d ' ')\" = 1",
                "-name '*.zip' | wc -l | tr -d ' ')\" = 1",
                "-name '*.AppImage' | wc -l | tr -d ' ')\" = 1",
                "test -f BUILD-SBOM-windows-x64.json",
                "test -f BUILD-SBOM-linux-x86_64.json"):
            with self.subTest(required=required):
                self.assertIn(required, promote["run"])

    def test_the_checksum_manifest_is_gpg_signed_on_the_publish_path(self):
        """SHA256SUMS is CI-generated; its signature proves which key released it."""
        sign = next(step for step in self.data["jobs"]["checksums"]["steps"]
                    if step.get("name") == "Sign the checksum manifest with the release key")
        self.assertEqual(sign["if"], "${{ inputs.publish }}")
        self.assertIn("GPG_PRIVATE_KEY", sign["run"])
        self.assertIn("SHA256SUMS.asc", sign["run"])
        self.assertIn("SIGNING.md", sign["run"])
        release_verify = next(step for step in self.data["jobs"]["release"]["steps"]
                              if step.get("name") == "Verify downloaded release bytes")
        self.assertIn("gpg --verify SHA256SUMS.asc SHA256SUMS", release_verify["run"])
        self.assertIn("signing-key.asc", release_verify["run"])

    def test_every_asset_carries_a_sigstore_build_attestation(self):
        checksums = self.data["jobs"]["checksums"]
        self.assertEqual(checksums["permissions"].get("id-token"), "write")
        self.assertEqual(checksums["permissions"].get("attestations"), "write")
        attest = next(step for step in checksums["steps"]
                      if "attest-build-provenance" in step.get("uses", ""))
        self.assertRegex(attest["uses"], r"@[0-9a-f]{40}$")
        self.assertEqual(attest["with"]["subject-path"], "dist/*")

    def test_no_second_publish_path_exists(self):
        """The retired per-platform workflows stay retired."""
        self.assertFalse((ROOT / ".github/workflows/build-windows.yml").is_file(),
                         "build-windows.yml is retired; the unified pipeline builds Windows")
        self.assertFalse((ROOT / ".github/workflows/build-linux.yml").is_file(),
                         "build-linux.yml is retired; the unified pipeline builds Linux")
        for recipe in all_workflows():
            if recipe.name == "build-candidate.yml":
                continue
            self.assertNotIn("gh release create",
                             recipe.read_text(encoding="utf-8"),
                             f"{recipe.name} must not publish a release")


class ReleaseNotesTests(unittest.TestCase):
    """What a downloader reads must not describe the build as two different things.

    v0.4.12 was published saying it was "notarized by Apple" AND "Unsigned,
    unnotarized test build" on consecutive lines, because the template emitted a
    hardcoded unsigned line regardless of which mode had just been chosen. The
    release notes are the first thing anyone reads, and nobody re-reads them.

    Deliberately NOT gated on PyYAML: this renders the template with the shell that
    runs it in CI, so it needs nothing but bash.
    """

    @classmethod
    def setUpClass(cls):
        cls.text = ACTIVE.read_text(encoding="utf-8")

    def render(self, notarize: str) -> str:
        """Run the workflow's own notes block with one mode selected.

        The title is echoed alongside the notes so assertions can reach both.
        """
        # Keep the heredoc's own EOF terminator. Without it bash reads to the end of
        # input, so anything appended below - the title echo - becomes notes text.
        # The tag assignment is prepended because the split consumed it, and
        # release_title is built from it.
        body, _, _ = self.text.split('tag="v${VERSION}"', 1)[1].partition("          EOF")
        block = 'tag="v${VERSION}"\n' + body + "          EOF\n"
        script = block.replace("${{ inputs.notarize }}", notarize)
        # Print instead of writing notes.md, and drop the YAML indentation.
        script = script.replace("cat > notes.md <<EOF", "cat <<EOF")
        script = "\n".join(line[10:] if line.startswith(" " * 10) else line
                           for line in script.splitlines())
        runner = ("VERSION=9.9.9 GITHUB_REF_NAME=main GITHUB_SHA=abcdef1234567890\n"
                  + script + '\necho "TITLE=${release_title}"\n')
        # Never bash -c: Windows CreateProcess quoting mangles multiline -c
        # scripts into an exit-1/empty-stderr failure. run_bash_script writes
        # LF-terminated text to a file and executes that.
        result = run_bash_script(runner, cwd=ROOT, timeout=60)
        self.assertEqual(result.returncode, 0, result.stderr)
        return result.stdout

    def title_of(self, notarize: str) -> str:
        for line in self.render(notarize).splitlines():
            if line.startswith("TITLE="):
                return line[len("TITLE="):]
        self.fail("the block did not set release_title")

    def test_the_title_is_the_version_and_nothing_else(self):
        """A release name is an identity, not a provenance record."""
        for mode in ("true", "false"):
            with self.subTest(notarize=mode):
                self.assertEqual(self.title_of(mode), "v9.9.9")

    def test_a_notarized_release_does_not_also_claim_to_be_unsigned(self):
        body = self.render("true")
        self.assertIn("notarized by Apple", body)
        self.assertNotIn("Unsigned", body)
        self.assertNotIn("unnotarized", body)

    def test_a_test_build_says_it_is_unsigned(self):
        body = self.render("false")
        self.assertIn("Unsigned", body)
        self.assertNotIn("notarized by Apple", body)

    def test_the_notes_offer_every_platform_and_its_verification(self):
        """One release page carries macOS, Windows, Linux and how to verify them."""
        body = self.render("true")
        self.assertIn("Bitcoin-Easy-Signer-v9.9.9-macOS.dmg", body)
        self.assertIn("Bitcoin-Easy-Signer-v9.9.9-windows-x64.zip", body)
        self.assertIn("Bitcoin-Easy-Signer-v9.9.9-linux-x86_64.AppImage", body)
        self.assertIn("bitcoin-easy-multisig-signer-v9.9.9.tar.gz", body)
        self.assertIn("SHA256SUMS.asc", body)
        self.assertIn("signing-key.asc", body)
        self.assertIn("Sigstore", body)
        self.assertIn("SIGNING.md", body)

    def test_the_notes_carry_no_stale_version_specific_boilerplate(self):
        """v0.4.12 shipped a paragraph about a Sparrow/Nunchuk change-path patch."""
        for mode in ("true", "false"):
            with self.subTest(notarize=mode):
                body = self.render(mode)
                self.assertNotIn("Sparrow", body)
                self.assertNotIn("Nunchuk", body)

    def test_the_heading_is_the_version_alone(self):
        """Build provenance is not a release name; it belongs in the notes body."""
        body = self.render("true")
        self.assertIn("## v9.9.9", body)
        self.assertNotIn("— Apple Silicon", body)
        self.assertNotIn("— notarized", body)
        self.assertNotIn("— unsigned", body)

    def test_the_notes_name_the_network_the_app_actually_opens_on(self):
        """The notes described the pre-0.6.0 opening screen.

        They said "Mutinynet is the opening network", which 0.6.1 makes false. The
        notes are generated by this workflow, so a release would have told every
        downloader to expect the opposite of what they get.
        """
        for mode in ("true", "false"):
            with self.subTest(notarize=mode):
                body = self.render(mode)
                self.assertNotIn("Mutinynet is the opening network", body)
                self.assertIn("Opens on Bitcoin mainnet", body)
                self.assertIn("Enter Developer Mode", body)
                self.assertIn("the app reopens on mainnet", body)


if __name__ == "__main__":
    unittest.main()
